import { apiClient } from './apiClient'
import type { 
  Order, 
  OrderFilters, 
  OrderListResponse, 
  UpdateOrderStatusRequest,
  CreateOrderRequest,
  OrderStats
} from '../types/order'
import type { InvoiceDto } from '../types/invoice'
import { InvoiceService } from './invoiceService'

export class OrderService {
  private static readonly BASE_PATH = '/api/orders'

  /**
   * Lấy danh sách đơn hàng với filters và pagination
   */
  static async getOrders(
    filters: OrderFilters = {},
    page: number = 1,
    pageSize: number = 20
  ): Promise<OrderListResponse> {
    const params = new URLSearchParams()
    
    if (filters.status) params.append('status', filters.status)
    if (filters.search) params.append('search', filters.search)
    if (filters.dateFrom) params.append('dateFrom', filters.dateFrom)
    if (filters.dateTo) params.append('dateTo', filters.dateTo)
    if (filters.customerId) params.append('customerId', filters.customerId.toString())
    
    params.append('page', page.toString())
    params.append('pageSize', pageSize.toString())

    return await apiClient.get<OrderListResponse>(`${this.BASE_PATH}/filtered?${params}`)
  }

  /**
   * Lấy danh sách đơn hàng của customer hiện tại
   */
  static async getMyOrders(
    status?: string,
    page: number = 1,
    pageSize: number = 20
  ): Promise<OrderListResponse> {
    const params = new URLSearchParams()
    
    if (status && status !== 'all') params.append('status', status)
    params.append('page', page.toString())
    params.append('pageSize', pageSize.toString())

    return await apiClient.get<OrderListResponse>(`${this.BASE_PATH}/my-orders?${params}`)
  }

  /**
   * Lấy chi tiết đơn hàng theo ID
   */
  static async getOrderById(id: number): Promise<Order> {
    return await apiClient.get<Order>(`${this.BASE_PATH}/${id}`)
  }

  /**
   * Cập nhật trạng thái đơn hàng
   */
  static async updateOrderStatus(request: UpdateOrderStatusRequest): Promise<Order> {
    const updatedOrder = await apiClient.put<Order>(
      `${this.BASE_PATH}/${request.orderId}/status`,
      {
        status: request.status,
        notes: request.notes
      }
    )

    // Nếu trạng thái được cập nhật thành "Confirmed", 
    // hệ thống backend sẽ tự động tạo hóa đơn qua ProcessOrderConfirmationAsync
    if (request.status === 'Confirmed') {
      console.log('Order confirmed - Invoice will be automatically generated by backend')
    }

    return updatedOrder
  }

  /**
   * Lấy thông tin hóa đơn của đơn hàng (nếu có)
   */
  static async getOrderInvoice(orderId: number): Promise<InvoiceDto | null> {
    return await InvoiceService.getInvoiceByOrderId(orderId)
  }

  /**
   * Tạo hóa đơn thủ công cho đơn hàng
   */
  static async generateOrderInvoice(orderId: number, sendEmail: boolean = true): Promise<InvoiceDto> {
    return await InvoiceService.generateInvoice({ orderId, sendEmail })
  }

  /**
   * Tạo đơn hàng mới
   */
  static async createOrder(request: CreateOrderRequest): Promise<Order> {
    // apiClient.unwrapResponse already extracts the 'data' field from {success: true, data: order}
    return await apiClient.post<Order>(this.BASE_PATH, request)
  }

  /**
   * Xóa đơn hàng (chỉ với đơn hàng chưa xác nhận)
   */
  static async deleteOrder(id: number): Promise<void> {
    return await apiClient.delete<void>(`${this.BASE_PATH}/${id}`)
  }

  /**
   * Lấy thống kê đơn hàng
   */
  static async getOrderStats(): Promise<OrderStats> {
    return await apiClient.get<OrderStats>(`${this.BASE_PATH}/stats`)
  }

  /**
   * Export đơn hàng ra Excel (mock implementation)
   */
  static async exportOrders(filters: OrderFilters = {}): Promise<Blob> {
    // Mock implementation - trong thực tế sẽ gọi API để export
    const data = JSON.stringify(filters)
    return new Blob([data], { type: 'application/json' })
  }

  /**
   * Lấy danh sách trạng thái đơn hàng có thể chuyển đổi
   */
  static getAvailableStatusTransitions(currentStatus: string) {
    const statusFlow = {
      'Pending': ['Confirmed', 'Cancelled'],
      'Confirmed': ['Processing', 'Cancelled'],
      'Processing': ['Shipping', 'Cancelled'],
      'Shipping': ['Delivered', 'Returned'],
      'Delivered': ['Returned'],
      'Cancelled': [],
      'Returned': []
    }
    
    return statusFlow[currentStatus as keyof typeof statusFlow] || []
  }

  /**
   * Lấy label và màu cho trạng thái đơn hàng
   */
  static getStatusInfo(status: string) {
    const statusMap = {
      'Pending': { label: 'Chờ xác nhận', color: 'bg-yellow-100 text-yellow-800' },
      'Confirmed': { label: 'Đã xác nhận', color: 'bg-blue-100 text-blue-800' },
      'Processing': { label: 'Đang xử lý', color: 'bg-purple-100 text-purple-800' },
      'Shipping': { label: 'Đang giao hàng', color: 'bg-orange-100 text-orange-800' },
      'Delivered': { label: 'Đã giao hàng', color: 'bg-green-100 text-green-800' },
      'Cancelled': { label: 'Đã hủy', color: 'bg-red-100 text-red-800' },
      'Returned': { label: 'Đã trả hàng', color: 'bg-gray-100 text-gray-800' }
    }
    
    return statusMap[status as keyof typeof statusMap] || { 
      label: status, 
      color: 'bg-gray-100 text-gray-800' 
    }
  }

  /**
   * Lấy label và màu cho trạng thái thanh toán
   */
  static getPaymentStatusInfo(paymentStatus: string) {
    const statusMap = {
      'Pending': { label: 'Chưa thanh toán', color: 'bg-yellow-100 text-yellow-800' },
      'Paid': { label: 'Đã thanh toán', color: 'bg-green-100 text-green-800' },
      'Failed': { label: 'Thanh toán thất bại', color: 'bg-red-100 text-red-800' },
      'Refunded': { label: 'Đã hoàn tiền', color: 'bg-blue-100 text-blue-800' }
    }
    
    return statusMap[paymentStatus as keyof typeof statusMap] || { 
      label: paymentStatus, 
      color: 'bg-gray-100 text-gray-800' 
    }
  }

  /**
   * Thanh toán đơn hàng
   */
  static async payOrder(orderId: number): Promise<Order> {
    return await apiClient.post<Order>(`${this.BASE_PATH}/${orderId}/payment`)
  }
}

export default OrderService